#!/usr/bin/python
import time
print("\033[92m")

print("Məlumatlar hazırlanır...")
print("\033[92m")
print("\033[92m")
print("\033[92m")
time.sleep( 3 )
print("İstifadəçilərin kopyalanması : ")
print("\033[92m")
time.sleep( 1.5 )
print ("Qrup istifadəçilərini klonlamaq üçün")
time.sleep( 1.5 )
print ("- python3 kopyala.py")
time.sleep( 1.5 )
print ("əmrindən istifadə edin.")
print("\033[92m")
time.sleep( 1.5 )
print ("İlk istifadə zamanı telegrama təsdiq")
time.sleep( 1.5 )
print ("kodu gedəcək. Bu kodu bota daxil edin. ")
time.sleep( 1.5 )
print("\033[92m")
print ("Kodu təsdiqlədikdən sonra  ")
time.sleep( 1.5 )
print ("istifadəçilərini kopyalamaq ")
time.sleep( 1.5 )
print ("istədiyiniz qrupun qarşısındaki  ")
time.sleep( 1.5 )
print ("sıra nömrəsini yazıb Enter basın.")
time.sleep( 1.5 )
print("\033[92m")
print("\033[92m")
print("\033[92m")
print ("Kopyalanan istifadəçilərin daşınması : ")
time.sleep( 1.5 )
print("\033[92m")
time.sleep( 1.5 )
print ("Kopyalanmış faylların qrupa ")
time.sleep( 1.5 )
print ("daşınması üçün terminalda ")
time.sleep( 1.5 )
print ("- python3 dashi.py members.csv")
time.sleep( 1.5 )
print ("əmrini yazaraq Enter basın")
time.sleep( 1.5 )
print("\033[92m")
print ("Seçilmiş istifadəçiləri")
time.sleep( 1.5 )
print("qrupa daşımaq üçün qrup")
time.sleep( 1.5 )
print("sıra nömrəsini yazaraq Enter basın.") 
time.sleep( 1.5 )
print("\033[92m")
print("Bot seçtiyiniz qrupa. 1-5 saniyə intervalla istifadəçiləri əlavə edəcək") 
time.sleep( 1.5 )
print("\033[92m")
print("Botu dayandırmaq üçün : ctrl+x ") 
time.sleep( 1.5 )
print("\033[94m")
print("\033[94m")
print("Code by : @Texnoloq ") 
time.sleep( 5 )
